baseURL = 'https://p.karasov.net/'
languageCode = 'en-us'
title = 'Pavel Karasov'
theme = 'archie'

copyright = "by Pavel Karasov"

[pagination]
pagerSize = 4

[params]
	mode="auto" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	customCSS = ["css/fonts-cyrillic.css"]
	subtitle = "C# Developer, Architect, DevOps philosopher, lover of process optimization"
    
[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/ejsmile"

[[params.social]]
    name = "Linkedin"
    icon = "linkedin"
    url = "http://www.linkedin.com/in/pavel-karasov"

[[params.social]]
    name = "Gmail"
    icon = "mail"
    url = "mailto:pavel@karasov.net"

[[params.social]]
    name = "Telegram"
    icon = "message-circle"
    url = "https://t.me/PavelKarasov"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3